---
language: python
python:
  - 3.5
  - 3.6

before_install:
  - pip install setuptools

install:
  - python setup.py develop
  - pip install -r dev-requirements.txt

# No tests yet. Happily awaiting any contribution. :)
script:
  - echo TBD
#   - pytest
